/**
 * Quiz-related constants for the tutor application
 */

export const QUIZ_CONSTANTS = {
  DEFAULT_QUESTIONS: 15,
  MIN_QUESTIONS: 5,
  MAX_QUESTIONS: 20,
  MIN_AGE: 6,
  MAX_AGE: 14,
  TIME_PER_QUESTION_SECONDS: 36, // 36 seconds per question (approximately 2 minutes for 15 questions)
} as const;

export const DIFFICULTY_LEVELS = {
  BASIC: 'Basic',
  ADVANCED: 'Advanced',
  EXPERT: 'Expert',
  MIX: 'Mix',
} as const;

export const LANGUAGES = {
  HINDI: 'Hindi',
  ENGLISH: 'English',
  HINGLISH: 'Hinglish',
} as const;

export const SUBJECTS = {
  HINDI: 'Hindi',
  ENGLISH: 'English',
  MATHS: 'Maths',
  EVS_SCIENCE: 'EVS / Science',
  GENERAL_KNOWLEDGE: 'General Knowledge',
  CURRENT_AFFAIRS: 'Current Affairs',
  CHESS: 'Chess',
  OTHER: 'Other',
} as const;

export const HINDI_SUBTOPICS = [
  'Varnmala / Swar & Vyanjan',
  'Sangya (noun)',
  'Sarvanaam (pronoun)',
  'Kriya (verb)',
  'Visheshan (adjective)',
  'Muhavare / Lokoktiyan',
  'Reading comprehension (short passage)',
  'Kavita (poetry)',
  'Kahani (story)',
  'Vyakarana basics',
  'Shabd Rachna (word formation)',
  'Pad Parichay',
] as const;

export const ENGLISH_SUBTOPICS = [
  'Vocabulary',
  'Grammar (noun, verb, adjective, tense basics)',
  'Spelling',
  'Synonyms & antonyms',
  'Simple reading comprehension',
  'Punctuation',
  'Sentence structure',
  'Parts of speech',
  'Tenses (present, past, future)',
  'Articles (a, an, the)',
  'Prepositions',
  'Story writing basics',
] as const;

export const MATHS_SUBTOPICS = [
  'Addition & subtraction',
  'Multiplication & division',
  'Fractions (basic)',
  'Decimals (basic)',
  'Word problems (age-appropriate)',
  'Geometry basics (shapes, area/perimeter)',
  'Number system',
  'Place value',
  'Measurement (length, weight, volume)',
  'Time & calendar',
  'Money & currency',
  'Data handling (graphs, charts)',
  'Patterns & sequences',
  'Mental math',
] as const;

export const EVS_SCIENCE_SUBTOPICS = [
  'Plants & animals',
  'Human body basics',
  'Environment & pollution',
  'Seasons & weather',
  'Solar system',
  'Food & nutrition',
  'Water cycle',
  'Natural resources',
  'Safety & first aid',
  'Habitats & ecosystems',
  'Matter & materials',
  'Energy & force',
  'Simple machines',
  'Health & hygiene',
] as const;

export const GENERAL_KNOWLEDGE_SUBTOPICS = [
  'India (states, capitals, famous places)',
  'World (countries, capitals, flags – basic)',
  'Sports',
  'Famous personalities',
  'Inventions & discoveries',
  'Festivals & celebrations',
  'Monuments & landmarks',
  'Rivers & mountains',
  'Books & authors',
  'Movies & entertainment',
  'Technology & computers',
  'Nature & wildlife',
  'History basics',
  'Geography basics',
] as const;

export const CURRENT_AFFAIRS_SUBTOPICS = [
  'National News',
  'International News',
  'Sports Updates',
  'Science & Technology',
  'Environment & Climate',
  'Space & Astronomy',
  'Awards & Honors',
  'Government & Politics',
  'Education & Schools',
  'Health & Medicine',
  'Economy & Business',
  'Culture & Arts',
  'Social Issues',
  'Recent Events',
] as const;

export const CHESS_SUBTOPICS = [
  // Basic Rules & Special Moves
  'Castling',
  'En Passant',
  'Pawn Promotion',
  'Special Power Moves',
  'Chess Notation',
  'Piece Values',
  
  // Checkmate Patterns
  'Mate with Rook',
  'Mate with Queen',
  'Mate with Two Bishops',
  'Mate with Knight and Bishop',
  'Mate in One',
  'Mate in Two',
  'Smothered Mate',
  'Anastasia\'s Mate',
  'Arabian Mate',
  'Boden\'s Mate',
  'Scholar\'s Mate',
  'Fool\'s Mate',
  'Legal\'s Mate',
  'Blackburne\'s Mate',
  'Greco\'s Mate',
  'Lolli\'s Mate',
  'Opera Mate',
  'Swiss Mate',
  'Corner Mate',
  'Epaulette Mate',
  'Dovetail Mate',
  'Kill Box Mate',
  'Triangle Mate',
  'Balestra Mate',
  'Cozio\'s Mate',
  'Damiano\'s Mate',
  'Stalemate',
  
  // Tactics
  'Double Attack',
  'Pin',
  'Knight Fork',
  'Skewer',
  'Discovered Attack and Discovered Check',
  'Back Rank',
  'Windmill',
  'Zugzwang',
  'Perpetual Check',
  'Opening Traps',
  'Tactical Combinations',
  'Fork & Pin Tactics',
  'Sacrifice Strategies',
  'Exchange Tactics',
  
  // Endgames
  'Pawn Endgame',
  'Rook Endgames',
  'Queen Endgames',
  'Bishop vs Knight',
  'King in Endgame',
  
  // Strategy & Positional Play
  'Opening Strategies',
  'Middle Game Tactics',
  'Endgame Techniques',
  'Checkmate Patterns',
  'Pawn Structures',
  'Piece Coordination',
  'Attack & Defense',
  'Positional Play',
  'King Safety',
  'Piece Development',
  'Control of Center',
  'Defense Strategies',
  'Counterattack',
  'Weak Squares',
  'Outpost',
  'Pawn Breaks',
  'Piece Activity',
  'Centralization',
  'Basic Opening Principles',
  
  // Popular Openings
  'King\'s Gambit',
  'Queen\'s Gambit',
  'Sicilian Defense',
  'French Defense',
  'Caro-Kann Defense',
  'Italian Game',
  'Spanish Game (Ruy Lopez)',
  'London System',
  'Scandinavian Defense',
  'Alekhine Defense',
  'Nimzo-Indian Defense',
  'Queen\'s Indian Defense',
  'Grünfeld Defense',
  'Benoni Defense',
  'Pirc Defense',
  'Modern Defense',
  'Dutch Defense',
  'English Opening',
  'Reti Opening',
  'Bird\'s Opening',
  'Larsen\'s Opening',
  'Benko Gambit',
  'Evans Gambit',
  'Danish Gambit',
  'Budapest Gambit',
  'Albin Counter-Gambit',
  'Marshall Attack',
  'Fried Liver Attack',
  'Two Knights Defense',
  'Philidor Defense',
  'Petrov Defense',
  'Scotch Game',
  'Four Knights Game',
  'Three Knights Game',
  'Vienna Game',
  'King\'s Indian Attack',
  'Stonewall Attack',
  'Colle System',
  'Torre Attack',
  'Catalan Opening',
  'Trompowsky Attack',
  'Polish Opening',
  'Sokolsky Opening',
  'Grob\'s Attack',
  'Barnes Opening',
  'Amar Opening',
  'Dunst Opening',
  'Van\'t Kruijs Opening',
  'Saragossa Opening',
  'Clemenz Opening',
  'Ware Opening',
  'Mieses Opening',
  'Basman Defense',
  'St. George Defense',
  'Staunton Gambit',
  'From Gambit',
  'Baltic Defense',
  'Elephant Gambit',
  'Latvian Gambit',
  'Halloween Gambit',
  'Jerome Gambit',
  'Blackmar-Diemer Gambit',
  'Smith-Morra Gambit',
  'Wing Gambit',
  'Englund Gambit',
  
  // Sicilian Defense Variations
  'Dragon Variation',
  'Najdorf Variation',
  'Scheveningen Variation',
  'Taimanov Variation',
  'Kan Variation',
  'Accelerated Dragon',
  'Hyperaccelerated Dragon',
  'Maroczy Bind',
  'English Attack',
  'Keres Attack',
  'Yugoslav Attack',
  'Sozin Attack',
  'Velimirovic Attack',
  'Rauzer Attack',
  'Richter-Rauzer Attack',
  'Boleslavsky Variation',
  'Sveshnikov Variation',
  'Kalashnikov Variation',
  'Pelikan Variation',
  'Chelyabinsk Variation',
  'Löwenthal Variation',
  'Paulsen Variation',
  'Four Knights Variation',
  'Pin Variation',
  'Alapin Variation',
  'Classical Variation',
  'Morphy Defense',
  'Steinitz Defense',
  'Classical Defense',
  'Breyer Defense',
  'Zaitsev Defense',
  'Chigorin Defense',
  'Marshall Defense',
  'Schliemann Defense',
  'Jaenisch Gambit',
  'Schwartz Defense',
  'Cozio Defense',
  'Bird Defense',
  
  // Learning & Practice
  'Chess Puzzles',
  'Famous Chess Games',
  'Time Management',
] as const;

export const MESSAGES = {
  GREETING: 'Hello! Welcome to your AI Quiz Tutor! 👋',
  AGE_PROMPT: 'What is your age?',
  LANGUAGE_PROMPT:
    'Which language should I use for questions: Hindi, English, or Hinglish (mix)?',
  SUBJECT_PROMPT:
    'Which subject do you want: Hindi, English, Maths, EVS / Science, General Knowledge, Current Affairs, Chess, or Something else (Other)?',
  SUBTOPIC_PROMPT: 'Great! Now choose a subtopic:',
  QUIZ_START: 'Great, I will ask you 5 questions on',
  QUIZ_INSTRUCTIONS:
    'You have 3 minutes to answer all 5 questions. Click on A, B, C or D to select your answer. Click Submit when done! 🎉',
  CORRECT_RESPONSE: 'Correct! ✅',
  INCORRECT_RESPONSE: 'Nice try, but the correct answer is',
  QUIZ_COMPLETED: 'Quiz completed! 🎉',
  SCORE_MESSAGE: 'You answered',
  OUT_OF: 'out of 5 questions correctly.',
  MOTIVATIONAL: 'Good job! Practice thoda aur karenge to aur better hoga.',
  ANOTHER_QUIZ: 'Do you want to try another quiz on the same topic or a different topic?',
} as const;

